### ISSUE TITLE
Easy way to make it work on windows.

### ISSUE THREAD

**Issue by red-ornob** [terokarvinen/micro-run#5]
Might be abandoned but might as well.

On line 36:
`cmd = string.format("python3 '%s'", filename)`

It calls the command `python3`, for windows the command for python is `py`.
Simply changing it from `python3` to `py` fixes it and allows it to work on windows.

Idk if there is an easy way to figure out the OS and call a different command, or if it's easier to just have different versions.

Edit: Easy to implement for windows users* I suppose,
Not sure how easy it is to implement in the code to work alongside linux.

**Comment by terokarvinen** [comment]
As stated in README, the main platform for micro-run is Linux. For Windows, you can create a wrapper script or similar to call 'py' from 'python3'. 

I don't currently have a Windows to test it, and full Windows support is not a feature of this plugin. I might consider this as a feature request for major feature upgrades.
